### ISSUE TITLE
Creating run-scenario.bat to run integration tests in Windows

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/apim-test-integration#43]
**Tasks**
- Include Maven Install
- Include JAVA_HOME Setting
- Include Git Install
- Clone Product Repo
- Do changes in master-datasources.xml, copy db jdbc jar, etc
- Zip and copy the modified pack in /target folder
- Run integration tests

**Comment by kasunbg** [comment]
After a discussion, we thought to write a python script that is interoperable between different environments (Windows/Linux). @chaminda is working on that.
